fixtures:
  symlinks:
    yp: "#{source_dir}"
  forge_modules:
    augeas_core:
      repo: "puppetlabs/augeas_core"
      ref: "1.1.1"
    bodgitlib:
      repo: "bodgit/bodgitlib"
      ref: "3.0.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "6.2.0"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.5.0"
