fixtures:
  symlinks:
    yp: "#{source_dir}"
  forge_modules:
    augeas_core:
      repo: "puppetlabs/augeas_core"
      ref: "1.1.1"
    bodgitlib:
      repo: "bodgit/bodgitlib"
      ref: "2.0.1"
    concat:
      repo: "puppetlabs/concat"
      ref: "4.2.1"
    ip:
      repo: "thrnio/ip"
      ref: "1.0.1"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.25.1"
